# Managed by tfroot-github (gh-dependabot.tf); local edits are overwritten.
"updates":
- "directory": "/"
  "groups":
    "github-actions":
      "patterns":
      - "*"
  "package-ecosystem": "github-actions"
  "schedule":
    "interval": "daily"
- "directory": "/gh-cli"
  "groups":
    "docker":
      "patterns":
      - "*"
  "package-ecosystem": "docker"
  "schedule":
    "interval": "daily"
- "directory": "/tfroot-runner"
  "groups":
    "docker":
      "patterns":
      - "*"
  "package-ecosystem": "docker"
  "schedule":
    "interval": "daily"
"version": 2
